// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2fs6FvTV9aBFetDKI5EHHOGg8OE96_PE',
    appId: '1:721269281346:web:5c0da7cc4c29cd90ff93db',
    messagingSenderId: '721269281346',
    projectId: 'chatapp8181',
    authDomain: 'chatapp8181.firebaseapp.com',
    storageBucket: 'chatapp8181.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2CknpiI6S7rCdu56bWjkEZeUGmI_3Tgc',
    appId: '1:721269281346:android:18ba7cbbcc352de5ff93db',
    messagingSenderId: '721269281346',
    projectId: 'chatapp8181',
    storageBucket: 'chatapp8181.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUEXXdz9eIT3dMc5GzfRLfWqEVCccu8dg',
    appId: '1:721269281346:ios:bfa928ec5c8928faff93db',
    messagingSenderId: '721269281346',
    projectId: 'chatapp8181',
    storageBucket: 'chatapp8181.appspot.com',
    androidClientId: '721269281346-kbh9qvlvn822pkrkjngahrp7kae1311f.apps.googleusercontent.com',
    iosClientId: '721269281346-qrpru1b4f1lh4p2vqh1slunq91ii1ib2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUEXXdz9eIT3dMc5GzfRLfWqEVCccu8dg',
    appId: '1:721269281346:ios:51b9dfe76ba5ae8bff93db',
    messagingSenderId: '721269281346',
    projectId: 'chatapp8181',
    storageBucket: 'chatapp8181.appspot.com',
    androidClientId: '721269281346-kbh9qvlvn822pkrkjngahrp7kae1311f.apps.googleusercontent.com',
    iosClientId: '721269281346-rlr7eeqood3q93hro9ei7oqrvf9mihi2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
